import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter_application_1/config/environment_manager.dart';
import 'package:payhere_mobilesdk_flutter/payhere_mobilesdk_flutter.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

/// PayHere Mobile (Android / iOS) service.
///
/// Merchant ID and sandbox/live mode come from the .env files via
/// EnvironmentManager (PAYHERE_MERCHANT_ID, PAYHERE_SANDBOX).
/// The hash is generated by the `generate-payhere-hash` Edge Function,
/// which uses the PayHere *App* merchant secret for platform = 'mobile'.
class PayHereService {
  final SupabaseClient _supabase = Supabase.instance.client;

  /// Start payment flow.
  /// Returns the PayHere payment/order id on success, or null on
  /// cancel / failure. Never throws.
  Future<String?> startSubscriptionPayment({
    required int salonId,
    required String planName,
    required double amount,
    required String customerEmail,
    required String customerName,
    required String customerPhone,
  }) async {
    try {
      final env = EnvironmentManager();

      // 1. Generate order ID
      final orderId = 'SUB-$salonId-${DateTime.now().millisecondsSinceEpoch}';

      // 2. Get hash from Supabase Edge Function
      final String hash;
      try {
        final hashResponse = await _supabase.functions.invoke(
          'generate-payhere-hash',
          body: {
            'order_id': orderId,
            'amount': amount,
            'currency': 'LKR',
            'platform': 'mobile',
          },
        );
        hash = hashResponse.data['hash'] as String;
      } on FunctionException catch (e) {
        // invoke() throws on non-2xx responses
        debugPrint(
          '❌ generate-payhere-hash failed: status=${e.status}, details=${e.details}',
        );
        return null;
      }

      // 3. Build payment object
      final nameParts = customerName.trim().split(' ');
      final paymentObject = <String, dynamic>{
        'sandbox': env.payhereSandbox,
        'merchant_id': env.payhereMerchantId,
        'notify_url': '${env.supabaseUrl}/functions/v1/payhere-webhook',
        'order_id': orderId,
        'items': '$planName Subscription',
        'amount': amount.toStringAsFixed(2),
        'currency': 'LKR',
        'hash': hash,
        'first_name': nameParts.first,
        'last_name': nameParts.length > 1 ? nameParts.last : '',
        'email': customerEmail,
        'phone': customerPhone,
        'address': 'Colombo',
        'city': 'Colombo',
        'country': 'Sri Lanka',
        'custom_1': salonId.toString(),
        'custom_2': planName,
      };

      // 4. Start payment.
      // The SDK is callback-based, so wait for a callback with a Completer
      // (returning a plain variable here would always give null).
      final completer = Completer<String?>();

      PayHere.startPayment(
        paymentObject,
        (paymentId) {
          debugPrint('✅ PayHere completed: $paymentId');
          if (!completer.isCompleted) completer.complete(paymentId.toString());
        },
        (error) {
          debugPrint('❌ PayHere error: $error');
          if (!completer.isCompleted) completer.complete(null);
        },
        () {
          debugPrint('⏹️ PayHere dismissed');
          if (!completer.isCompleted) completer.complete(null);
        },
      );

      return await completer.future.timeout(
        const Duration(minutes: 5),
        onTimeout: () {
          debugPrint('⏱️ PayHere timed out waiting for callback');
          return null;
        },
      );
    } catch (e) {
      debugPrint('PayHere error: $e');
      return null;
    }
  }
}