// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnllE8MwHPRHDlEjo50_fMrzwyxNlvq-c',
    appId: '1:624521405165:web:09323a1025f02b668262e4',
    messagingSenderId: '624521405165',
    projectId: 'saloonf-ba359',
    authDomain: 'saloonf-ba359.firebaseapp.com',
    storageBucket: 'saloonf-ba359.firebasestorage.app',
    measurementId: 'G-925VW9Z44F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5U3XRktxs1WAZmvXZsoOg02ghUUFfKI',
    appId: '1:624521405165:android:1677551f7c46cfcd8262e4',
    messagingSenderId: '624521405165',
    projectId: 'saloonf-ba359',
    storageBucket: 'saloonf-ba359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk1qGSekjtKxs34q2CqzBzNppBRwi6A-8',
    appId: '1:624521405165:ios:a5e345a8c7ab20688262e4',
    messagingSenderId: '624521405165',
    projectId: 'saloonf-ba359',
    storageBucket: 'saloonf-ba359.firebasestorage.app',
    iosClientId: '624521405165-jh9c2a5bja9h8imm04j10pih75b2ps7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
